# Name of the "thing" to build
TARGET  = GLSchool.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

VPATH = ../Common
# Source code files used in this project

# Add any additional files to this line
SRCS    = GLBlanker.c \
	GLBlanker_GUI.c \
	GLBlanker_Prefs.c \
	GLBlanker.c \
	yarandom.c 

# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
