# Name of the "thing" to build
TARGET  = GLSchool.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

# Source code files used in this project
# Add any additional files to this line

SRCS    = GLBlanker.c \
	GLBlanker_GUI.c \
	GLBlanker_Prefs.c \
	glschool.c \
	glschool_alg.c \
	glschool_gl.c \
	../Common/yarandom.c \
	../Common/colors.c \
	../Common/hsv.c \
	../Common/tube.c \
	../Common/sphere.c


# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
