# Name of the "thing" to build
TARGET  = GLKnots.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

VPATH = ../Common

# Source code files used in this project
# Add any additional files to this line
SRCS = GLKnotsModule.c \
	glknots.c \
	GLBlanker_GUI.c \
	GLBlanker_Prefs.c \
	yarandom.c \
	tube.c \
	rotator.c \
	trackball.c \
	gltrackball.c \
	colors.c \
	hsv.c

# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
