# Name of the "thing" to build
TARGET  = GLBlockTube.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lpng16 -lz -lm

# Source code files used in this project
# Add any additional files to this line

SRCS = GLBlockTubeModule.c \
	GLBlockTube_GUI.c \
	GLBlockTube_Prefs.c \
	blocktube.c \
	blocktube_data.c \
	../Common/yarandom.c \
	../Common/xi_image.c

# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common

