# Name of the "thing" to build
TARGET  = GLBoxed.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

# Source code files used in this project
# Add any additional files to this line

SRCS    = GLBlanker.c \
	GLBlanker_GUI.c \
	GLBlanker_Prefs.c \
	boxed.c \
	../Common/yarandom.c


# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
