# Name of the "thing" to build
TARGET  = GLMatrix.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lpng12 -lz -lm

# Source code files used in this project
# Add any additional files to this line

SRCS = GLMatrixModule.c \
	GLMatrixModule_GUI.c \
	GLMatrix_Prefs.c \
	glmatrix.c \
	matrix_data.c \
	../Common/yarandom.c \
	../Common/xi_image.c

# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
