# Name of the "thing" to build
TARGET  = GLMatrix.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lpng16 -lz -lm

VPATH = ../Common

# Source code files used in this project
# Add any additional files to this line
SRCS = GLMatrixModule.c \
	GLMatrixModule_GUI.c \
	GLMatrix_Prefs.c \
	glmatrix.c \
	matrix_data.c \
	yarandom.c \
	xi_image.c

# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
