# Name of the "thing" to build
TARGET  = GLCubenetic.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

# Source code files used in this project
# Add any additional files to this line

SRCS    = GLBlanker.c \
	GLBlanker_GUI.c \
	GLBlanker_Prefs.c \
	cubenetic.c \
	../Common/yarandom.c \
	../Common/rotator.c \
	../Common/gltrackball.c \
	../Common/trackball.c \
	../Common/colors.c \
	../Common/hsv.c


# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
