# Name of the "thing" to build
TARGET  = GLCubenetic.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

VPATH = ../Common

# Source code files used in this project
# Add any additional files to this line
SRCS    = GLBlanker.c \
	GLBlanker_GUI.c \
	GLBlanker_Prefs.c \
	cubenetic.c \
	yarandom.c \
	rotator.c \
	gltrackball.c \
	trackball.c \
	colors.c \
	hsv.c


# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
