# Name of the "thing" to build
TARGET  = GLHyperTorus.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

# Source code files used in this project
# Add any additional files to this line

SRCS    = GLHyperTorus.c \
	GLHyperTorus_GUI.c \
	GLHyperTorus_Prefs.c \
	hypertorus.c \
	../Common/yarandom.c \
	../Common/trackball.c \
	../Common/gltrackball.c

# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common

