# Name of the "thing" to build
TARGET  = GLFlurry.blanker

# Additional linker libraries
LIBS    = -lGL -lGLU -lm

# Source code files used in this project
# Add any additional files to this line

SRCS    = flurry-smoke.c \
	flurry-spark.c \
	flurry-star.c \
	flurry-texture.c \
	flurry.c \
	GLFlurry.c \
	GLFlurry_GUI.c \
	GLFlurry_Prefs.c \
	../Common/yarandom.c \
	../Common/rotator.c \
	../Common/trackball.c

#SRCS    = blanker.c bitmap.c

# -------------------------------------------------------------
# Nothing should need changing below this line
-include ../Makefile.common
